Pipeline {
    stages {
        stage ("Git Repo") {
            steps {
                 git branch: 'master', url: 'https://github.com/asrathour12/DevopsProject.git'
            }
        }
    }
}
  
	  stage('Docker Build') {
    	agent any
      steps {
      	sh 'docker build -t devopsproject .'
      }
    }
  }
}

    stage('Docker Push') {
    	agent any
      steps {
      	withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
        	sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh 'docker push asrathour12/devopsproject:v1'
        }
      }
    }
  }
}